tembo-io/tembo-stacks

charts/conductor/dashboards/cnpg-dashboard.json

This PR will add a useful CNPG based dashboard to the data-plane clusters Grafana instances.
This dashboard was taken from [here](https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/grafana-configmap.yaml)

Add a CNPG based dashboard to Grafana

---

charts/conductor/templates/postgres-dashboard.yaml

If we have too many dashboards, it will cause the `ConfigMap` update to fail due to the size being too large for a single `ConfigMap`.
Move every dashboard into their own specific `ConfigMap`

move dashboard to generate their own configmaps

---

tembo-operator/src/cloudnativepg/cnpg.rs

https://cloudnative-pg.io/documentation/1.20/kubernetes_upgrade/#single-instance-clusters-with-reusepvc-set-to-false
> As long as a database service downtime is acceptable for your environment, draining the node is as simple as setting the nodeMaintenanceWindow to inProgress: true and reusePVC: true. This will allow the instance to be deleted and recreated as soon as the original PVC is available (e.g. with node local storage, as soon as the node is back up).
Currently, the k8s cluster doesn't scale down because the pod disruption budgets from CNPG prevent it. CNPG's logic is to prevent a node from being scaled down unless all the CNPG clusters on it have this setting enabled. Adding this configuration will allow cluster to scale down during the configured maintenance window. Leaving it …

[TEM-1407] Allow nodes to be scaled down by default

---

conductor/.gitignore
conductor/Dockerfile

```
error: failed to compile `conductor v0.1.0 (/build)`, intermediate artifacts can be found at `/build/target`
Caused by:
package `time v0.3.24` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.66.1
Either upgrade to rustc 1.67.0 or newer, or use
cargo update -p time@0.3.24 --precise ver
where `ver` is the latest version of `time` supporting rustc 1.66.1
The command '/bin/sh -c cargo install --path .' returned a non-zero code: 101
```

Update rust version conductor

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/Dockerfile
tembo-operator/src/controller.rs
tembo-operator/src/main.rs
tembo-operator/src/telemetry.rs

Adding support for enabling the tracing feature.
* Our controller already has a compile time flag to enable tracing, you must set `OPENTELEMETRY_ENDPOINT_URL` as an env var.
* Updating `Dockerfile` to use latest stable version of Rust and Alpine
* Update `telemetry.rs` code and crates for better telemetry and trace pattern usage.
* Update k8s-openapi and kube-rs crates
* Update code to work with updates crates.

Add support for enabling traces

---

conductor/Cargo.lock
conductor/Cargo.toml
tembo-pod-init/Cargo.toml
tembo-pod-init/src/watcher.rs

With the tracing changes to `tembo-operator` we had to bump the `kube` and `k8s-openapi` crate.  Since both `conductor` and `tembo-pod-init` use the `controller` crate we also need to bump those crates in each of these projects to be compatable.

Fix build issues with latest version of tembo-operator

---

charts/tembo-operator/templates/crd.yaml
tembo-operator/src/defaults.rs
tembo-operator/src/extensions.rs

Only specify `SCHEMA` in the `CREATE EXTENSION` statement when its explicitly provided.
Refactored part of `toggle_extensions()` in order to add tests around this functionality.

make extension schema specification optional

---

tembo-operator/src/extensions.rs

Add name mappings for:
- https://pgt.dev/extensions/pgemailaddr
- https://pgt.dev/extensions/pg_financial
- https://pgt.dev/extensions/pg_roaringbitmap
- https://pgt.dev/extensions/pg_semver
- https://pgt.dev/extensions/pgsql_http
- https://pgt.dev/extensions/pgsql_ogr_fdw
- https://pgt.dev/extensions/pg_timeit
- https://pgt.dev/extensions/pguint
- https://pgt.dev/extensions/pguri
- https://pgt.dev/extensions/postgres_decoderbufs
- https://pgt.dev/extensions/postgresql_anonymizer
- https://pgt.dev/extensions/postgresql_hll
- https://pgt.dev/extensions/postgresql_topn
- https://pgt.dev/extensions/postgresql_unit
- https://pgt.dev/extensions/uuid_ossp

Add more extension name mappings

---

tembo-operator/src/controller.rs
tembo-operator/src/deployment_postgres_exporter.rs
tembo-operator/src/postgres_exporter.rs

The previous logic will always add a volume to the deployment mainly because `cdb.spec.metrics` is never empty by default, or at least shouldn't be.  New logic should handle the case correctly, where we only want to mount the `ConfgMap` if there are configured queries.
```
spec:
metrics:
enabled: true
image: quay.io/prometheuscommunity/postgres-exporter:v0.12.0
```

fix logic where we add metrics volume

---

tembo-operator/src/deployment_postgres_exporter.rs

Correct logic to follow the same pattern as `exporter_volumes`.  This should make sure that no `volumeMounts` are created unless there are `volumes` to mount.

Do not add `volumeMount` if there isn't a `volume`

---

tembo-operator/src/controller.rs

We want to notice manually changed extensions at least once per minute

Check for manually changed extensions every minute

---

tembo-operator/src/cloudnativepg/cnpg.rs

Fix backup schedule to be daily instead of hourly
Related: https://github.com/cloudnative-pg/cloudnative-pg/pull/2593

Fix backup schedule to include seconds

---

tembo-operator/justfile
tembo-operator/src/cloudnativepg/cnpg.rs
tembo-operator/src/defaults.rs
tembo-operator/tests/integration_tests.rs

This PR is meant to add the ability to enable HA/Replication Slots configuration into the Tembo Cloud stack.
* The operator will now automatically enable HA when 2 or more replicas are set in the `CoreDBSpec`.
* We now respect the value of `replicas` and it will set the replica/instance count from `spec.replicas`
Fixes: [TEM-1384](https://linear.app/tembo/issue/TEM-1384)

Enable HA/Replication Slots

---

conductor/src/errors.rs
conductor/src/lib.rs

This PR should fix the issue where we see weird/non-standard connection string data in the UI.
I believe the data that was being rendered with this logic was causing the issue.
```
match data.get(field) {
Some(k8s_openapi::ByteString(vec)) => {
let string_data = std::str::from_utf8(vec)
.map_err(|_| ConductorError::ParsingPostgresConnectionError)?;
Ok(string_data.to_string())
}
None => Err(ConductorError::PostgresConnectionInfoNotFound),
}
}
```
* Simplify how we get the username and password.
* Write a test for the `get_field_value_from_secret` function to make sure the data we parse is valid.

fix how we return connection string info

---

conductor/src/main.rs
conductor/src/types.rs
conductor/testdata/operator-values.yaml

If you have a cluster and click a lot of extension installs or toggles, then you delete your cluster, there could be a situation where an update event comes in after the delete event since we requeue the update event when extensions are still processing. There is no need to requeue, we can just return the current status, and the ad-hoc updates will return the extensions status as they become available. Still, we can wait for all extensions to be ready during Create, so that clusters go from Submitted to Created only after all initially requested extensions are ready.

Don't wait for extensions to finish in an Update event

---

charts/tembo-pod-init/templates/self-signed-certs.yaml
tembo-pod-init/justfile
tembo-pod-init/testdata/cnpg.yaml
tembo-pod-init/testdata/operator-values.yaml
tembo-pod-init/testdata/pod-init.yaml
tembo-pod-init/testdata/reloader.yaml

* Update `justfile` to have better support for local development
* Update the helm chart self-signed certificate template to set `rotationPolicy: Always`.  You can read more about this setting [here](https://cert-manager.io/docs/usage/certificate/#the-rotationpolicy-setting)
fixes: [TEM-1600](https://linear.app/tembo/issue/TEM-1600/issue-with-renewing-certs-with-pod-init)

Local dev updates, Helm chart updates

---

stacks/standard.yaml

Replace `tembo-pg-cnpg` image with `standard-cnpg` image.

Use `standard-cnpg` image in Standard Stack

---

tembo-operator/Cargo.toml
tembo-operator/src/controller.rs

Small change, I noticed sometimes we get updates from control plane all at once, this results in the extensions always reconciling in bursts, which just made things slightly slower

Avoid bursts of reconciliation

---

charts/tembo-operator/templates/crd.yaml
stacks/machine_learning.yaml
stacks/message_queue.yaml
stacks/olap.yaml
stacks/oltp.yaml
stacks/standard.yaml
tembo-operator/src/defaults.rs

Bump image to `standard-cnpg:15.3.0-1-0c19c7e` in the following stacks:
- `Standard`
- `MessageQueue`
- `OLAP`
- `OLTP`

Bump to standard-cnpg:15.3.0-1-0c19c7e

---

tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/apis/postgres_parameters.rs
tembo-operator/tests/integration_tests.rs

This PR covers extensions that require load and require create extension, but not extensions that require load and not create extension.
Allows enabling these extensions
```
citus
pg_cron
pg_later
pglogical
pglogical_ticker
pg_net
pg_tle
plrust
timescaledb
```

Auto-enable libraries for extensions that require load

---

.github/actions/find-changed-directories/action.yml
.github/actions/publish-crate/action.yml
.github/workflows/cargo_publish.yml
conductor/Cargo.lock
conductor/Cargo.toml
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-pod-init/Cargo.toml

The workflow should identify any crate in the repo, so setting every Cargo.toml to `publish = false` except for the tembo-operator.

add action and workflow to publish controller

---

charts/tembo-operator/templates/crd.yaml
conductor/Cargo.lock
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/apis/postgres_parameters.rs
tembo-operator/src/stacks/types.rs

Use the Stacks struct from the `Stacks` API instead of coredb types, which requires update to the crd. It is a non-breaking change because all the new attributes on `Stack` are optional.

replace coredb Stack w/ Stacks def

---

charts/tembo-operator/templates/crd.yaml
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/justfile
tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/cloudnativepg/mod.rs
tembo-operator/src/controller.rs

First change needed to add PITR 
This change adds `first_recoverability_time` field to the `CoreDBStatus`.  This exposes the earliest full backup we could potentially restore to and will be needed to calculate the dates and times in the UI to do a PITR.
This also removes unneeded telemetry spans that are already in place with the `#[instrument]` macros.
fixes: [TEM-1809](https://linear.app/tembo/issue/TEM-1809/add-first-recoverability-point-to-status)

Expose first recovery point time to CoreDB status

---

.github/workflows/operator.yaml
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/justfile
tembo-operator/src/cloudnativepg/cnpg.rs

- Add requeue when getting cluster in `unfence_pod` function. This resolves a stack overflow issue that arose in integration tests in certain PRs
- Drop `--release` flag from `cargo run` in Justfile and CI

[bugfix] Requeue for `cluster.get` in `unfence_pod`

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/cloudnativepg/cnpg.rs

- Add requeue when getting cluster in get_fenced_pods function. This resolves a stack overflow issue that arose in integration tests in certain PRs
- Similar to https://github.com/tembo-io/tembo-stacks/pull/278

Fix cluster.get in get_fenced_pods

---

.github/workflows/operator.yaml
charts/tembo-operator/templates/crd.yaml
conductor/Cargo.lock
conductor/src/main.rs
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/justfile
tembo-operator/scripts/remove-minio.sh
tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/cloudnativepg/cnpg.rs
tembo-operator/src/controller.rs
tembo-operator/src/defaults.rs
tembo-operator/src/errors.rs
tembo-operator/src/extensions/install.rs
tembo-operator/testdata/minio-bucket-job.yaml
tembo-operator/testdata/minio-secret.yaml
tembo-operator/testdata/minio.yaml
tembo-operator/testdata/pod-init.yaml
tembo-operator/tests/integration_tests.rs
tembo-operator/yaml/sample-machine-learning-backup.yaml
tembo-operator/yaml/sample-standard-backup.yaml
tembo-operator/yaml/sample-standard-restore.yaml

Restore work will be split up into a few different PR's.  This change adds basic restore capabilities into the controller.
* Add support to run Minio locally to test backup and restores with. ([TEM-1834](https://linear.app/tembo/issue/TEM-1834/add-ability-to-add-tests-for-backups-and-restores))
* Add integration test to run an instance, add some data, back it up then restore it and check if the data is on the new restored instance.
* Adds support into the operator for non-AWS S3 compatible object storage (Minio, DigitalOcean, etc)
* Basic support to restore an instance from a backup in the `CoreDBSpec`.
** Reconciling a set of extensions into the restored instance and Conductor support will come in a later PR's
fixes: [TEM-1379](https://linear.app/tembo/issue/TEM-1379/bootstrap-from-config …

[tembo-operator] Add instance restore capabilities into operator

---

conductor/src/lib.rs

to look up namespaces we use labels instead of annotations https://docs.rs/kube/latest/kube/api/struct.ListParams.html

Use labels instead of annotations for namespace

---

tembo-operator/Cargo.toml
tembo-operator/testdata/minio.yaml

Minio by default as a requests for 16GB of memory.  This removes that requirement so it can run more normally on a local system.

Remove resource requirement from minio

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/justfile

Allow for configurable storage class in `just annotate`. Examples:
- `just --set STORAGE_CLASS_NAME gp2 install-dependencies`
- `just annotate gp2`
Related to:
- https://github.com/tembo-io/website/pull/106

Allow for configurable storage class in `just annotate`

---

conductor/Cargo.lock
conductor/src/lib.rs
conductor/src/main.rs
conductor/src/status_reporter.rs
conductor/src/types.rs

Add `pooler_host` field to `ConnectionInfo`. This information is passed up to the control-plane.

Add `pooler_host` to `ConnectionInfo` in conductor

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/cloudnativepg/cnpg.rs

According to [CNPG's docs](https://cloudnative-pg.io/documentation/1.21/cloudnative-pg.v1/#postgresql-cnpg-io-v1-BootstrapRecovery), the `app` user and database should be set by default.  For some reason they are being set as an empty string value instead.  For now, set the correct values in the operator.

Forcibly set the app user and database into the ClusterBootstrapRecovery configuration 

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/extensions/types.rs

For PITR to copy the extensions and trunk installs from the original instance we need to convert the `ExtensionStatus` and `TrunkInstallStatus` values back into usable types to input into the new restored instance.

Add convert methods to Extensions and TrunkInstall

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/postgres_certificates.rs

Longer-named instances have too long a common name, so we can use the shorter common name instead, and allow the domain name to live in the dnsNames configuration.

Pick shorter name for common name

---

.github/workflows/operator.yaml
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/cloudnativepg/cnpg.rs
tembo-operator/src/controller.rs
tembo-operator/src/extensions/database_queries.rs
tembo-operator/src/postgres_certificates.rs
tembo-operator/tests/integration_tests.rs

There is an issue with setting up the `-pooler` secret since we switched to using our own generated CA.  This PR is an attempt to add support to generate the certificate and secret the pooler requires to reconcile along with setting up the `cnpg_pooler_pgbouncer` role in the database.
fixes: [TEM-2039](https://linear.app/tembo/issue/TEM-2039/fix-pooler-mode-to-work-with-custom-certs)

Correct issue with setting up CA and Secret for Connection Pooler

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/controller.rs
tembo-operator/src/heartbeat.rs
tembo-operator/src/lib.rs
tembo-operator/tests/integration_tests.rs

We have seen where instances cannot be restored due to little to no transactions taking place, essentially an empty database.  The issue is that a date and time can be requested, but since there are no transactions during that time you want to restore to the restore will fail.
This adds a new schema (tembo) and a function that will write a timestamp to a table (heartbeat_timestamp).
Feel free to make suggestions on how things should be named.
fixes: [TEM-2132](https://linear.app/tembo/issue/TEM-2132/pitr-will-fail-on-instances-with-zero-transactions)

Add heartbeat table to ensure PITR will work on databases with no transactions

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/cloudnativepg/cnpg.rs

Due to the manner and timing of when we reconcile the connection pooler, an issue can occur where the pooler cannot finish reconciliation and thus the extension reconciliation cannot be reconciled so that we can unfence the restored pod.  This check should allow for the pooler to not reconcile unless the main CNPG pod is fully online and ready for traffic.
fixes: [TEM-2133](https://linear.app/tembo/issue/TEM-2133/pitr-will-fail-if-connection-pooler-is-enabled-during-restore)

If connection pooler is enabled, a restore will not get fully reconciled.

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/extensions/database_queries.rs
tembo-operator/tests/integration_tests.rs

If we have the restartedAt annotation, and the pod is older than this annotation, and the pod has been not ready for over 30 seconds, delete the pod.
This case is applicable to queries that do not handle the smart or fast postgres shutdown procedures. For example executing a PL/Python function that's long running is not interrupted even by fast shutdown, and instead needs immediate shutdown.

fix: Instances stuck restarting for non-interruptible, long-running queries

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/stacks/config_engines.rs
tembo-operator/src/stacks/templates/message_queue.yaml
tembo-operator/src/stacks/types.rs

set shared_buffers at a different proportion than other Stacks

MQ config engine

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/cloudnativepg/cnpg.rs

Due to issues decompressing bzip2 backups and WAL archives on large backups, switching to snappy compression allows for a faster compression and decompression time.
fixes: [TEM-2232](https://linear.app/tembo/issue/TEM-2232/restoring-for-s3-backups-is-slow-and-fails)

switch backup and wal compression to use snappy

---

tembo-operator/Cargo.toml
tembo-operator/Dockerfile

In a move to a more generic build, we need to disable the telemetry flag.  Eventually we will move this to a run time configuration, but for now we need to disable it so others outside of Tembo can run our operator in a more generic way that can be tailored to their infrastructure needs.
Fixes: [TEM-2276](https://linear.app/tembo/issue/TEM-2276/disable-telemetry-flag-in-operator)

do not build with telemetry flag

---

charts/tembo-operator/templates/crd.yaml
tembo-operator/Cargo.toml
tembo-operator/src/app_service/manager.rs
tembo-operator/src/app_service/types.rs
tembo-operator/yaml/sample-document.yaml

- (Cargo.toml) Bump version from 0.19.2 to 0.20.0.
- (manager.rs) Refactor generate_deployment function to accommodate app service storage configurations, including volume mounts.
- (types.rs) Introduce StorageConfig struct to handle volumes and volume mounts.
- (types.rs) Update AppService struct to include storage as an optional field.
- Add a new yaml/sample-document.yaml

Update operator storage configuration for App Services

---

charts/tembo-operator/templates/crd.yaml
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/crdgen.rs

This change is needed due to the nature of a Helm chart's lifecycle.  To make sure the cluster does not delete specific critical resources, we need to keep the CRDs in place even if the Helm chart is deleted.  This is specifically for migration purposes.  If the CRDs are no longer needed then a manual deletion of the CRDs is still possible.  
Issue: [TEM-2028](https://linear.app/tembo/issue/TEM-2028/tembo-operator-oss-user-experience)

Annotation to keep CRDs

---

charts/tembo-operator/templates/deployment.yaml
charts/tembo-operator/values.yaml

temp operator deployments resources are hardcoded inside helm templates - this changes moves the hardcoding to values.yaml allowing users to override the values

move tembo operator deployment resources configurable
