tembo-io/tembo-stacks

conductor/justfile
conductor/testdata/operator-values.yaml
conductor/testdata/pod-init.yaml
conductor/tests/integration_tests.rs

Since switching completely over to CNPG, Conductor tests have been failing. This PR is an attempt to get tests working again.

[conductor] Fix tests

---

charts/tembo-operator/templates/crd.yaml
conductor/testdata/operator-values.yaml
conductor/tests/integration_tests.rs
tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/extensions/database_queries.rs
tembo-operator/src/extensions/kubernetes_queries.rs
tembo-operator/src/extensions/toggle.rs
tembo-operator/src/extensions/types.rs

Accidentally undid some changes from this PR https://github.com/tembo-io/tembo-stacks/pull/188

Schema optional

---

tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/apis/postgres_parameters.rs
tembo-operator/src/controller.rs
tembo-operator/src/extensions/database_queries.rs
tembo-operator/src/extensions/kubernetes_queries.rs
tembo-operator/src/extensions/toggle.rs
tembo-operator/src/extensions/types.rs
tembo-operator/src/psql.rs

Status was flipping back and forth from having error_message as null or not included.

Fix issue with status flapping

---

conductor/src/errors.rs
conductor/src/lib.rs
conductor/src/main.rs
conductor/src/routes/health.rs
conductor/src/routes/mod.rs
conductor/src/status_reporter.rs
conductor/tests/integration_tests.rs

Watch for changes in resources, and report back to control plane any change

Continuous status reporting

---

charts/tembo-operator/templates/cnpg-prometheusrules.yaml
charts/tembo-operator/values.yaml

Add `PrometheusRule` for CNPG based instances.

Add PrometheusRules

---

charts/tembo-operator/templates/crd.yaml
conductor/src/extensions.rs
tembo-operator/.gitignore
tembo-operator/Cargo.toml
tembo-operator/justfile
tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/apis/postgres_parameters.rs
tembo-operator/src/cloudnativepg/cnpg.rs
tembo-operator/src/controller.rs
tembo-operator/src/exec.rs
tembo-operator/src/extensions/database_queries.rs
tembo-operator/src/extensions/kubernetes_queries.rs
tembo-operator/src/extensions/toggle.rs
tembo-operator/src/extensions/types.rs

These recent changes are not passing QA in dev, so reverting them out until I can resolve the issues

Revert shared libraries changes

---

tembo-operator/src/extensions/install.rs

Fix issue where we need a default unwrap for `ext_status`

handle empty status

---

charts/tembo-operator/templates/crd.yaml
tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/controller.rs
tembo-operator/src/errors.rs
tembo-operator/src/ingress.rs
tembo-operator/tests/integration_tests.rs

Allows end users to configure extra domain names to be respected by SNI routing

Add extra domains option

---

tembo-operator/Cargo.toml
tembo-operator/src/cloudnativepg/clusters.rs

https://github.com/tembo-io/tembo-stacks/pull/248#discussion_r1327369694

Update ClusterStatus definition

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/apis/postgres_parameters.rs

should fix: https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fapi.tembo.io%2Fapi-docs%2Fopenapi.json

add trait to ConfigValue

---

tembo-operator/Cargo.toml
tembo-operator/src/stacks/templates/machine_learning.yaml
tembo-operator/src/stacks/templates/message_queue.yaml
tembo-operator/src/stacks/templates/olap.yaml
tembo-operator/src/stacks/templates/oltp.yaml
tembo-operator/src/stacks/templates/standard.yaml

- Bump standard-cnpg images to `15.3.0-1-45c2054`
- Bump ml-cnpg image to `15.3.0-1-a3e532d`

Bump standard-cnpg tag to `15.3.0-1-45c2054`

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/yaml/sample-machine-learning.yaml
tembo-operator/yaml/sample-message-queue.yaml
tembo-operator/yaml/sample-olap.yaml
tembo-operator/yaml/sample-oltp.yaml
tembo-operator/yaml/sample-standard.yaml

Add sample definitions for local development, or anyone trying the Tembo Operator. These examples are good starting points for anyone looking to build out their own custom spec.

Add sample definitions for local development

---

dataplane-webserver/src/lib.rs
dataplane-webserver/src/main.rs
dataplane-webserver/src/routes/secrets.rs
dataplane-webserver/src/secrets/mod.rs
dataplane-webserver/src/secrets/types.rs

So that we can build another API version in a subsequent change
in a separate pr doing same thing for metrics right now. Then will add new API

Move secrets Data API into separate module

---

tembo-operator/src/cloudnativepg/cnpg.rs

Fix `restartedAt` comparison: was previously using the value from the new cluster spec being created in `reconcile_cnpg`.
Based off of previous work done with @sjmiller609 on #300.

operator: compare CNPG `restartedAt` using the current spec

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/apis/coredb_types.rs

Add `ToSchema` to resolve control plane docs test failures.

Add ToSchema to ConnectionPooler

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/ingress.rs
tembo-operator/src/lib.rs

allows use the same input validation logic

Allow control plane import ingress

---

conductor/Cargo.lock
conductor/src/main.rs
conductor/src/types.rs

Create new event types `Restore` & `Restored` for PITR

Create new event type to handle PITR

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/stacks/templates/machine_learning.yaml
tembo-operator/src/stacks/templates/message_queue.yaml
tembo-operator/src/stacks/templates/olap.yaml
tembo-operator/src/stacks/templates/oltp.yaml
tembo-operator/src/stacks/templates/standard.yaml

- Bump `standard-cnpg` images to `15.3.0-1-1096aeb`
- Bump `ml-cnpg` image to `15.3.0-1-93dae54 `

Bump `standard-cnpg` tag to `15.3.0-1-1096aeb`

---

charts/tembo-operator/templates/crd.yaml
conductor/Cargo.lock
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/app_service/ingress.rs
tembo-operator/src/app_service/manager.rs
tembo-operator/src/app_service/types.rs
tembo-operator/src/psql.rs
tembo-operator/tests/integration_tests.rs
tembo-operator/yaml/sample-postgrest.yaml

- add for replacePathRegex for more granular  ingress routes
- create 1 Service for each appService instead of 1 for each port

add replacePathRegex middleware support, patch appService ports

---

charts/tembo-operator/templates/crd.yaml
tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/apis/coredb_types.rs
tembo-operator/src/controller.rs
tembo-operator/src/extensions/database_queries.rs
tembo-operator/src/stacks/config_engines.rs

```
➜  tembo-operator git:(more-data-in-status) k get -o yaml coredb | grep -E 'master|fully'
last_fully_reconciled_at: "2023-11-10T21:56:44.218940Z"
pg_postmaster_start_time: "2023-11-10T17:42:51.000917387Z"
➜  tembo-operator git:(more-data-in-status) k get -o yaml coredb | grep -E 'master|fully'
last_fully_reconciled_at: "2023-11-10T21:58:12.025896Z"
pg_postmaster_start_time: "2023-11-10T17:42:51.000917387Z"
```

More data in status

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/cloudnativepg/cnpg.rs
tembo-operator/src/controller.rs

Fix issue where pooler is not deleted when disabled.

Fix pooler reconcile logic

---

tembo-operator/Cargo.lock
tembo-operator/Cargo.toml
tembo-operator/src/app_service/manager.rs
tembo-operator/src/cloudnativepg/cnpg.rs
tembo-operator/src/extensions/types.rs

This PR adds a way to run some sql after create extension.

Default setting for pg_cron
